# 测试配置 - 简化版本用于排查启动问题
server:
  port: 8080

spring:
  # 临时禁用数据源自动配置
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  # Redis配置保持简单
  redis:
    public:
      database: 0
      host: localhost
      port: 6379
      timeout: 5000
      password: ""
    config:
      database: 2
      host: localhost
      port: 6379
      timeout: 5000
      password: ""
    address:
      database: 3
      host: localhost
      port: 6379
      timeout: 5000
      password: ""
    lettuce:
      pool:
        max-active: 10
        max-wait: 10000
        max-idle: 5
        min-idle: 3

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# MyBatisPlus配置（简化）
mybatis-plus:
  typeAliasesPackage: com.ruoyi.**.domain
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl