# 数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        druid:
            # 主库数据源
            master:
              url: jdbc:mysql://123.56.89.151:3306/numbercard?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&autoReconnect=true&failOverReadOnly=false&allowPublicKeyRetrieval=true
              username: root
              password: 94loaUawkU0SuUJV@
            # 从库数据源
            slave:
                # 从数据源开关/默认关闭
                enabled: false
                url: 
                username: 
                password: 
            # 初始连接数
            initialSize: 5
            # 最小连接池数量
            minIdle: 10
            # 最大连接池数量
            maxActive: 100
            # 配置获取连接等待超时的时间
            maxWait: 60000
            # 配置连接超时时间
            connectTimeout: 30000
            # 配置网络超时时间
            socketTimeout: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            minEvictableIdleTimeMillis: 300000
            # 配置一个连接在池中最大生存的时间，单位是毫秒
            maxEvictableIdleTimeMillis: 900000
            # 配置检测连接是否有效
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            webStatFilter: 
                enabled: true
            statViewServlet:
                enabled: true
                # 设置白名单，不填则允许所有访问
                allow:
                url-pattern: /druid/*
                # 控制台管理用户名和密码
                login-username: ruoyi
                login-password: 123456
            filter:
                stat:
                    enabled: true
                    # 慢SQL记录
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true

    # redis 配置
    redis:
        public:
          database: 1
          host: test.sdzdf.com
          port: 8006
          password: sdzdfredis20241206
          timeout: 5000
        config:
            database: 2
            host: test.sdzdf.com
            port: 8006
            password: sdzdfredis20241206
            timeout: 5000
        address:
            database: 3
            host: test.sdzdf.com
            port: 8006
            password: sdzdfredis20241206
            timeout: 5000
        lettuce:
            pool:
                max-active: 10
                max-wait: 10000
                max-idle: 5
                min-idle: 3


submit:
    h5: https://h5.haoka.asia/
    url: https://api.haoka.asia/api/order/submitInfo
    callback: https://api.haoka.asia/api/callback/commonCallback
    shop: https://shop.haoka.asia/